# BS =================================
```{r, eval = F}
library(SolowVariants)
theme_set(theme_bw())

# Setting up the parameter grid ---------------------------------
aux_np <- 200
aux_parameter_grid <-
  create_parameter_grid(
    c("B", "alpha", "delta", "n", "s"),
    c(10, 1 / 3, 0.1, 0.005, 0.22),
    c(NA, NA, NA, NA, NA),
    c(NA, NA, NA, NA, NA),
    aux_np
  )

# Setting starting values for K and L ---------------------------------
aux_startvalues <- list(K = 1, L = 1)

# Simulate the basic Solow growth model ---------------------------------
aux_simulation <- SimulateBasicSolowModel(aux_parameter_grid, aux_np,aux_startvalues)

# Visualise some variables ---------------------------------
VisualiseSimulation(aux_simulation,
                    c("YpW", "Y", "KpW"), 
                    "free")

# Verify whether the economy is 'in' steady state in the final period ---------------------------------

steadystate_checker(aux_simulation, aux_parameter_grid, "BS")
# Draw transition diagram ---------------------------------
draw_transition_diagram(list(B = c(1),
                             alpha = 1/3, 
                             delta = 0.2, 
                             n = 0.005, 
                             s = c(0.25, 0.05)), "BS"
```
# GS =================================
```{r, eval = F}
library(SolowVariants)
theme_set(theme_bw())

# Setting up the parameter grid ---------------------------------
aux_np <- 200
aux_parameter_grid <-
  create_parameter_grid(
    c("g", "alpha", "delta", "n", "s"),
    c(0.02, 1 / 3, 0.1, 0.005, 0.22),
    c(NA, NA, NA, NA, NA),
    c(NA, NA, NA, NA, NA),
    aux_np
  )

# Setting starting values for K and L ---------------------------------
aux_startvalues <- list(A = 1, K = 1, L = 1)

# Simulate the basic Solow growth model ---------------------------------
aux_simulation <- SimulateGeneralSolowModel(aux_parameter_grid, aux_np,aux_startvalues)

# Visualise some variables ---------------------------------
VisualiseSimulation(aux_simulation,
                    c("YpW", "Y", "KpEW"), 
                    "free")

# Verify whether the economy is 'in' steady state in the final period ---------------------------------

steadystate_checker(aux_simulation, aux_parameter_grid, "GS")

```
# ESHC =================================
```{r, eval = F}
library(SolowVariants)
theme_set(theme_bw())

# Setting up the parameter grid ---------------------------------
aux_np <- 200
aux_parameter_grid <-
  create_parameter_grid(
    c("alpha", "phi", "n", "g", "sK", "sH", "delta"),
    c(1 / 3, 1 / 3, 0.005, 0.02, 0.15, 0.15, 0.2),
    c(NA, NA, NA, NA, NA, NA, NA),
    c(NA, NA, NA, NA, NA, NA, NA),
    aux_np
  )

# Setting starting values for K and L ---------------------------------
aux_startvalues <- list(A = 1, K = 1, L = 1, H = 1)

# Simulate the basic Solow growth model ---------------------------------
aux_simulation <- SimulateExtendedSolowModelHumanCapital(aux_parameter_grid, aux_np,aux_startvalues)

# Visualise some variables ---------------------------------
VisualiseSimulation(aux_simulation,
                    c("YpW", "KpEW", "HpEW"), 
                    "free")

# Verify whether the economy is 'in' steady state in the final period ---------------------------------

steadystate_checker(aux_simulation, aux_parameter_grid, "ESHC")

```
# ESSOE =================================
```{r, eval = F}
library(SolowVariants)
theme_set(theme_bw())

# Setting up the parameter grid ---------------------------------
aux_np <- 200
getRequiredParams("ESSOE")
getRequiredStartingValues("ESSOE")
aux_parameter_grid <-
  create_parameter_grid(
    c("B", "alpha", "n", "s", "r"),
    c(1, 1 / 3, 0.005, 0.2, 0.04),
    c(NA, NA, NA, NA, NA),
    c(NA, NA, NA, NA, NA),
    aux_np
  )

# Setting starting values for K and L ---------------------------------
aux_startvalues <- list(L = 1, V = 1)

# Simulate the basic Solow growth model ---------------------------------
aux_simulation <- SimulateExtendedSolowModelSmallOpenEconomy(aux_parameter_grid, aux_np,aux_startvalues)

# Visualise some variables ---------------------------------
VisualiseSimulation(aux_simulation,
                    c("YpW", "KpEW", "VpEW"), 
                    "free")

# Verify whether the economy is 'in' steady state in the final period ---------------------------------

steadystate_checker(aux_simulation, aux_parameter_grid, "ESSOE")

# Draw transition diagram ---------------------------------
draw_transition_diagram(list(B = 0.01,
                             alpha = c(1/3,2/3), 
                             n = 0.05, 
                             s = c(0.45, 0.05),
                             r = 0.03,
                             w = 2), "ESSOE")

```
# ESSRO =================================
```{r, eval = F}
library(SolowVariants)
theme_set(theme_bw())

# Setting up the parameter grid ---------------------------------
aux_np <- 200
aux_parameter_grid <-
  create_parameter_grid(
    c("alpha", "beta", "n", "g", "sE", "s", "delta"),
    c(1 / 3, 1 / 3, 0.005, 0.02, 0.15, 0.15, 0.2),
    c(NA, NA, NA, NA, NA, NA, NA),
    c(NA, NA, NA, NA, NA, NA, NA),
    aux_np
  )

# Setting starting values for K and L ---------------------------------
aux_startvalues <- list(A = 1, K = 1, L = 1, R = 1)

# Simulate the basic Solow growth model ---------------------------------
aux_simulation <- SimulateExtendedSolowModelScarceResourceOil(aux_parameter_grid, aux_np,aux_startvalues)

# Visualise some variables ---------------------------------
VisualiseSimulation(aux_simulation,
                    c("YpW", "KpEW", "R"), 
                    "free")

# Verify whether the economy is 'in' steady state in the final period ---------------------------------

steadystate_checker(aux_simulation, aux_parameter_grid, "ESSRO")
```
# ESSRL =================================
```{r, eval = F}
library(SolowVariants)
theme_set(theme_bw())

# Setting up the parameter grid ---------------------------------
aux_np <- 200
aux_parameter_grid <-
  create_parameter_grid(
    c("alpha", "beta", "delta", "n", "s", "g", "X"),
    c(1/3, 1/3, 0.2, 0.005, 0.2, 0.02, 1),
    c(NA, NA, NA, NA, NA, NA, NA),
    c(NA, NA, NA, NA, NA, NA, NA),
    aux_np
  )

# Setting starting values for K and L ---------------------------------
aux_startvalues <- list(A = 1, K = 1, L = 1)

# Simulate the basic Solow growth model ---------------------------------
aux_simulation <- SimulateExtendedSolowModelScarceResourceLand(aux_parameter_grid, aux_np,aux_startvalues)

# Visualise some variables ---------------------------------
VisualiseSimulation(aux_simulation,
                    c("YpW", "KpW", "L"), 
                    "free")

# Verify whether the economy is 'in' steady state in the final period ---------------------------------

steadystate_checker(aux_simulation, aux_parameter_grid, "ESSRL")

```

# ESSROL =================================
```{r, eval = F}
library(SolowVariants)
theme_set(theme_bw())

# Setting up the parameter grid ---------------------------------
aux_np <- 200
aux_parameter_grid <-
  create_parameter_grid(
    c("alpha", "beta", "kappa", "delta", "n", "s", "sE", "g", "X"),
    c(1/3, 1/3, 1/3, 0.2, 0.005, 0.2, 0.05, 0.02, 1),
    c(NA, NA, NA, NA, NA, NA, NA, NA, NA),
    c(NA, NA, NA, NA, NA, NA, NA, NA, NA),
    aux_np
  )

# Setting starting values for K and L ---------------------------------
aux_startvalues <- list(A = 1, K = 1, L = 1, R = 1)

# Simulate the basic Solow growth model ---------------------------------
aux_simulation <- SimulateExtendedSolowModelScarceResourceOilAndLand(aux_parameter_grid, aux_np,aux_startvalues)

# Visualise some variables ---------------------------------
VisualiseSimulation(aux_simulation,
                    c("YpW", "KpEW", "R"), 
                    "free")

# Verify whether the economy is 'in' steady state in the final period ---------------------------------

steadystate_checker(aux_simulation, aux_parameter_grid, "ESSROL")
```

# ESEG =================================
```{r, eval = F}
library(SolowVariants)
theme_set(theme_bw())

# Setting up the parameter grid ---------------------------------
aux_np <- 200
aux_parameter_grid <-
  create_parameter_grid(
    c("alpha", "phi", "delta", "n", "s"),
    c(1 / 3, 0.99, 0.15, 0, 0.22),
    c(NA, NA, NA, NA, NA),
    c(NA, NA, NA, NA, NA),
    aux_np
  )

# Setting starting values for K and L ---------------------------------
aux_startvalues <- list(K = 1, L = 1)

# Simulate the basic Solow growth model ---------------------------------
aux_simulation <- SimulateExtendedSolowModelEndogenousGrowth(aux_parameter_grid, aux_np, aux_startvalues)
# Visualise some variables ---------------------------------
VisualiseSimulation(
  aux_simulation,
  c("gYpW", "gKpW"),
  "free"
)

# Economy in SS in the End ---------------------------------

steadystate_checker(aux_simulation, aux_parameter_grid, "ESEG")

# Draw transition diagram ---------------------------------
#not yet written for ESEG
# draw_transition_diagram(
#   list(B = c(1),
#     alpha = 1/3, 
#     delta = 0.2, 
#     n = 0.005, 
#     s = c(0.25, 0.05)), 
#   "BS"
# )
```
# ESEGRomer =================================
```{r, eval = F}
library(SolowVariants)
theme_set(theme_bw())

# Setting up the parameter grid ---------------------------------
aux_np <- 500
aux_parameter_grid <- create_parameter_grid(
  c("alpha", "phi", "lambda", "rho", "s", "sR", "delta", "n"),
  c(1/3, 1, 0.2, 0.2, 0.2, 0.15, 0.15, 0.005),
  c(NA, NA, NA, NA, NA, NA, NA, NA),
  c(NA, NA, NA, NA, NA, NA, NA, NA),
  aux_np
)

# Setting starting values for K and L ---------------------------------
aux_startvalues <- list(A = 1, K = 1, L = 1)

# Simulate the basic Solow growth model ---------------------------------
aux_simulation <- SimulateExtendedSolowModelEndogenousGrowthRomer(aux_parameter_grid, aux_np, aux_startvalues)
# Visualise some variables ---------------------------------
VisualiseSimulation(
  aux_simulation,
  c("gYpW", "gKpW"),
  "free"
)

# Economy in SS in the end? ---------------------------------

steadystate_checker(aux_simulation, aux_parameter_grid, "ESEG")

# Draw transition diagram ---------------------------------
#not yet written for ESEG
# draw_transition_diagram(
#   list(B = c(1),
#     alpha = 1/3, 
#     delta = 0.2, 
#     n = 0.005, 
#     s = c(0.25, 0.05)), 
#   "BS"
# )
```
